<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<testcase id="RHEL7-83980">
    <title>rhsm.gui.tests.system_tests.error_dialog_and_no_traceback_when_network_is_down</title>
    <description>Given a system is registered
  and at least one subscription is attached
  and I have run 'subscription-manager-gui'
When the network goes down
  and I try to remove some subscription in 'My Subscriptions' tab
Then I should see a dialog 'Network is down'
  and no traceback appears in '/var/log/rhsm/rhsm.log'</description>
    <test-steps>
        <test-step>
            <test-step-column id="step"/>
        </test-step>
    </test-steps>
    <custom-fields>
        <custom-field id="caseautomation" content="automated"></custom-field>
        <custom-field id="caseimportance" content="high"></custom-field>
        <custom-field id="caselevel" content="component"></custom-field>
        <custom-field id="caseposneg" content="positive"></custom-field>
        <custom-field id="testtype" content="functional"></custom-field>
        <custom-field id="subtype1" content="-"></custom-field>
        <custom-field id="subtype2" content="-"></custom-field>
    </custom-fields>
</testcase>
